name: CI/CD

on:
  push:
    branches: 
      - main
    paths:
      - '.github/**'
      - '!docs/**'
      - 'src/**'
      - '*.sln'
      - '*.props'

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#      
#    - name: Setup Dotnet for use with actions
#      uses: actions/setup-dotnet@v3
#      with:
#        dotnet-version: '8.0.x'
#        
#    - name: Build with dotnet
#      run: dotnet build --configuration Release
      
  deploy:
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup Dotnet for use with actions
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        
      - name: Pack with dotnet
        run: dotnet pack --configuration Release
        
      - name: Push to nuget with dotnet
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols true  
