name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instalación de dependencias
      - name: Install Dependencies
        run: |
          npm install

      # 4. Ejecutar pruebas unitarias
      - name: Run Tests
        run: |
          npm test -- --coverage

      # 5. Configuración de SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.0.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=autoguru-au_kv-push
            -Dsonar.organization=autoguru-au
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
